### ISSUE TITLE
singletile:true on wms layers no effect

### ISSUE THREAD

**Issue by pvgenuchten** [wegue-oss/wegue#288]
i tried singletile wms  server in epsg:4326, but the service is loaded as tiles anyway (which is quite inconvenient on this service, although it leads to quite spectacular artwork)

```
{
          "type": "WMS",
          "lid": "gaez-AYP",
          "name": "GAEZ Actual Yields and Production",
          "format": "image/png",
          "layers": "res06%3AActual%20Yields%20and%20Production%20Symbology",
          "url": "https://gaez-services.fao.org/server/services/res06/ImageServer/WMSServer",
          "transparent": true,
          "singleTile": true,
          "projection": "EPSG:4326",
          "attribution": "<a href=\"https://fao.org\">FAO</a>",
          "isBaseLayer": false,
          "visible": false,
          "displayInLayerList": true
        }
```

![image](https://user-images.githubusercontent.com/299829/162981522-122057f7-38be-4906-aa81-f27508f5f47a.png)

**Comment by justb4** [comment]
Good catch! Looks like `singleTile` is not taken from the config in the [createWmsLayer factory function](https://github.com/meggsimum/wegue/blob/master/src/factory/Layer.js#L107). .. BUT I think `singleTile` is no longer supported in latest (v6) OL. Looks like there is a WMS-param `TILED` which is populated from the Wegue conf attr `tiled`. You may try `"tiled": false` in your config i.s.o. `singleTile`.

**Comment by chrismayer** [comment]
I think for loading single, untiled images there is a different source in OpenLayers, see https://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS-ImageWMS.html.

This is not reflected in Wegue, since [type `WMS` ends in `TileWMS` source](https://github.com/meggsimum/wegue/blob/master/src/factory/Layer.js#L110). But would be very much appreciated if someone would bring up a PR for that, if there is a need for single untiled image layers.

**Comment by justb4** [comment]
Ha, crossing comments! I also just found out the same!
